const translations = {
    en: {
        nav_features: "Features",
        nav_how: "How It Works",
        nav_roadmap: "Roadmap",
        nav_support: "Support",
        hero_title: "Learn Japanese Through<br><span class=\"highlight\">Real Content & AI Practice</span>",
        hero_subtitle: "Read authentic articles, build vocabulary with flashcards, and practice writing with AI-powered feedback that actually helps you improve.",
        coming_soon: "Coming Soon",
        problem_title: "Why Most Vocabulary Apps Don't Work",
        prob_context_title: "No Context",
        prob_context_desc: "Learning isolated words from textbook examples doesn't show you how Japanese is actually used.",
        prob_retention_title: "Poor Retention",
        prob_retention_desc: "Without spaced repetition, you forget words as fast as you learn them.",
        prob_practice_title: "No Production Practice",
        prob_practice_desc: "Recognizing words is easy. Using them correctly in sentences? That's the real challenge.",
        journey_title: "Comprehensive Learning Journey",
        feat_read_title: "📰 Read Real Japanese",
        feat_read_p1: "Browse authentic news articles written for native speakers. Tap any word for instant dictionary lookup with furigana reading guides.",
        feat_read_p2: "Our advanced <strong>Compound Word Breakdown</strong> technology analyzes complex Japanese terms, splitting them into easily understandable sub-components.",
        feat_read_p3: "One tap saves words to your personal deck for practice later. Learn vocabulary in the context it's actually used.",
        feat_dict_title: "🔍 Standalone Dictionary & Organization",
        feat_dict_p1: "Not just a reader—YominGo features a professional-grade standalone Japanese dictionary with Romaji support and intelligent multi-factor ranking.",
        feat_dict_p2: "Build <strong>User-Created Collections</strong> to neatly organize your vocabulary, and effortlessly bookmark your favorite articles for future reading.",
        feat_dict_img: "Organize your<br>Vocabulary Journey",
        feat_flash_title: "🎴 Smart Flashcards",
        feat_flash_p1: "Powered by the FSRS algorithm (the science behind Anki), cards appear exactly when you're about to forget them.",
        feat_flash_p2: "Experience <strong>Sense-Aware Flashcards</strong>: reviews and exercises are tied to the specific contextual meaning you found the word in.",
        feat_flash_p3: "Progressive difficulty: Kanji → Reading → Meaning. Filter by JLPT level (N5-N1) to focus on what matters for your goals.",
        feat_flash_img: "Screenshot: Flashcard interface<br>with JLPT filtering",
        feat_ai_title: "🤖 AI Writing Tutor",
        feat_ai_p1: "The real magic: Write Japanese sentences using your vocabulary, get detailed AI feedback on what you did right and what to improve.",
        feat_ai_p2: "Not just \"correct\" or \"wrong\"—get scored feedback on grammar, word choice, and natural usage. This is how you actually learn to use words, not just recognize them.",
        how_title: "How It Works",
        step1_title: "Read & Collect",
        step1_desc: "Browse articles, tap words you don't know, add them to your deck",
        step2_title: "Review Daily",
        step2_desc: "Flashcards appear based on spaced repetition—review what you're about to forget",
        step3_title: "Practice Writing",
        step3_desc: "Use your vocabulary in sentences, get AI feedback, improve your Japanese",
        step4_title: "Track Progress",
        step4_desc: "Watch your vocabulary grow and retention improve over time",
        road_title: "What's Now & What's Next",
        road_subtitle: "YominGo is built by one developer (me!) and actively growing. Here's what works today and what's coming soon.",
        live_now: "✓ Live Now",
        live_1: "Real Japanese News articles",
        live_2: "FSRS spaces repetition flashcards and AI powered Smart-cards!",
        live_3: "AI-powered writing exercises with detailed feedback",
        live_4: "Dictionary (beta) for instance word lookup",
        live_5: "Custom collections create using wide range of tags (JLPT, Common,Tech..etc)",
        live_6: "Multi-language support (english,chinese,korean and vietnamese)",
        coming_soon_col: "🚧 Coming Soon",
        soon_1: "Offline mode for studying anywhere",
        soon_2: "Custom user created article creation (from text and scanning images)",
        soon_3: "Grammer practice",
        soon_4: "Listening practice",
        support_title: "☕ Support Development",
        support_desc: "YominGo is built by one person in their spare time. If it's helping you learn Japanese,<br>consider buying me a coffee—it helps cover server costs and keeps new features coming!",
        footer_built: "Built with ❤️ for Japanese learners",
        footer_contact: "Contact",
        footer_privacy: "Privacy Policy"
    },
    ko: {
        nav_features: "기능",
        nav_how: "작동 방식",
        nav_roadmap: "로드맵",
        nav_support: "지원",
        hero_title: "실제 콘텐츠 및 AI 연습으로<br><span class=\"highlight\">일본어 배우기</span>",
        hero_subtitle: "실제 기사를 읽고 플래시 카드로 어휘를 쌓으며, AI 피드백을 통해 실제로 실력을 향상시키는 작문 연습을 해보세요.",
        coming_soon: "출시 예정",
        problem_title: "대부분의 단어 앱이 효과가 없는 이유",
        prob_context_title: "문맥 부족",
        prob_context_desc: "교과서 예문에서 단어를 따로 배우는 것은 일본어가 실제로 어떻게 사용되는지 보여주지 않습니다.",
        prob_retention_title: "낮은 기억 유지율",
        prob_retention_desc: "간격 반복(Spaced Repetition) 없이 배우면 금방 잊어버리게 됩니다.",
        prob_practice_title: "생산 연습 부족",
        prob_practice_desc: "단어를 알아보는 것은 쉽습니다. 문장에서 올바르게 사용하는 것이 진짜 도전입니다.",
        journey_title: "종합적인 학습 여정",
        feat_read_title: "📰 실제 일본어 읽기",
        feat_read_p1: "원어민을 위해 쓰여진 실제 뉴스 기사를 탐색하세요. 단어를 터치하여 즉시 사전을 찾고 후리가나를 볼 수 있습니다.",
        feat_read_p2: "저희의 고급 <strong>복합어 분석</strong> 기술은 복잡한 일본어 용어를 쉽게 이해할 수 있는 하위 구성 요소로 분할합니다.",
        feat_read_p3: "터치 한 번으로 개인 덱에 단어를 저장하여 나중에 연습하세요. 실제 사용되는 문맥에서 어휘를 배우십시오.",
        feat_dict_title: "🔍 독립형 사전 및 체계화",
        feat_dict_p1: "단순한 리더기가 아닙니다—YominGo는 로마자 지원 및 지능적인 다중 요인 순위 지정을 갖춘 전문가급 일본어 사전을 제공합니다.",
        feat_dict_p2: "<strong>사용자 생성 컬렉션</strong>을 만들어 어휘를 깔끔하게 정리하고, 좋아하는 기사를 나중에 읽을 수 있도록 북마크하세요.",
        feat_dict_img: "어휘 학습<br>체계화하기",
        feat_flash_title: "🎴 스마트 플래시카드",
        feat_flash_p1: "FSRS 알고리즘(Anki의 기반 기술)을 바탕으로, 잊어버리기 직전에 카드가 나타납니다.",
        feat_flash_p2: "<strong>문맥 인식 플래시카드</strong>를 경험해보세요: 복습 및 연습이 단순한 정의가 아닌 단어를 찾은 특정 문맥적 의미와 연결됩니다.",
        feat_flash_p3: "점진적 난이도: 한자 → 읽기 → 의미. JLPT 레벨(N5-N1)로 필터링하여 목표에 맞는 내용에 집중하세요.",
        feat_flash_img: "스크린샷: JLPT 필터링이 포함된<br>플래시카드 인터페이스",
        feat_ai_title: "🤖 AI 작문 튜터",
        feat_ai_p1: "진짜 마법: 단어를 사용하여 일본어 문장을 쓰면, 무엇을 잘했고 무엇을 개선해야 하는지 상세한 AI 피드백을 받을 수 있습니다.",
        feat_ai_p2: "단순히 '맞음'이나 '틀림'이 아닙니다—문법, 단어 선택, 자연스러운 표현에 대해 점수화된 피드백을 받으세요. 이것이 단어를 단순히 아는 것을 넘어 실제로 사용하는 방법입니다.",
        how_title: "작동 방식",
        step1_title: "읽기 및 수집",
        step1_desc: "기사를 탐색하고, 모르는 단어를 터치하여 덱에 추가하세요.",
        step2_title: "매일 복습",
        step2_desc: "간격 반복에 따라 플래시카드가 나타납니다—잊어버리기 직전에 복습하세요.",
        step3_title: "작문 연습",
        step3_desc: "문장에서 어휘를 사용하고, AI 피드백을 받아 일본어 실력을 향상시키세요.",
        step4_title: "진행 상황 추적",
        step4_desc: "시간이 지남에 따라 어휘가 늘어나고 기억력이 향상되는 것을 지켜보세요.",
        road_title: "현재와 미래",
        road_subtitle: "YominGo는 한 명의 개발자(저예요!)가 만들고 꾸준히 성장하고 있습니다. 현재 제공되는 기능과 곧 출시될 기능입니다.",
        live_now: "✓ 현재 기능",
        live_1: "실제 일본어 뉴스 기사",
        live_2: "FSRS 간격 반복 플래시카드 및 AI 기반 스마트 카드!",
        live_3: "상세한 피드백이 있는 AI 기반 작문 연습",
        live_4: "즉각적인 단어 검색을 위한 사전 (베타)",
        live_5: "다양한 태그(JLPT, 일반, 기술 등)를 사용한 맞춤형 컬렉션 생성",
        live_6: "다국어 지원 (영어, 중국어, 한국어, 베트남어)",
        coming_soon_col: "🚧 출시 예정",
        soon_1: "어디서나 공부할 수 있는 오프라인 모드",
        soon_2: "사용자 맞춤 기사 생성 (텍스트 및 이미지 스캔에서)",
        soon_3: "문법 연습",
        soon_4: "듣기 연습",
        support_title: "☕ 개발 지원",
        support_desc: "YominGo는 여가 시간에 한 사람이 만들었습니다. 일본어 학습에 도움이 된다면<br>커피 한 잔을 사주세요—서버 비용을 충당하고 새로운 기능을 추가하는 데 큰 도움이 됩니다!",
        footer_built: "일본어 학습자를 위해 ❤️로 만들었습니다",
        footer_contact: "문의하기",
        footer_privacy: "개인정보 보호정책"
    },
    zh: {
        nav_features: "功能",
        nav_how: "使用说明",
        nav_roadmap: "路线图",
        nav_support: "支持",
        hero_title: "通过真实语境与 AI 练习<br><span class=\"highlight\">学习日语</span>",
        hero_subtitle: "阅读真实的新闻文章，通过抽任卡积累词汇，并通过提供即时反馈的 AI 辅导练习写作，真正提高你的日语水平。",
        coming_soon: "敬请期待",
        problem_title: "为什么大多数单词应用没用",
        prob_context_title: "缺乏语境",
        prob_context_desc: "仅从教科书例句中孤立地学习单词，无法了解日语在现实中的实际用法。",
        prob_retention_title: "记忆留存率低",
        prob_retention_desc: "如果没有间隔重复，背过的单词很快就会被遗忘。",
        prob_practice_title: "缺乏输出练习",
        prob_practice_desc: "认出单词很容易。如何在句子中正确使用它们？这才是真正的挑战。",
        journey_title: "全面的学习旅程",
        feat_read_title: "📰 阅读真实日语",
        feat_read_p1: "浏览为母语者编写的真实新闻文章。点击任何单词即可进行即时词典查询并显示振假名阅读指南。",
        feat_read_p2: "我们先进的<strong>复合词拆分</strong>技术可分析复杂的日语词汇，将其拆分为易于理解的子成分。",
        feat_read_p3: "只需点击一下，即可将单词保存到您的个人牌组中以供日后练习。在实际使用的语境中学习词汇。",
        feat_dict_title: "🔍 独立词典与整理",
        feat_dict_p1: "不仅仅是一个阅读器——YominGo 配备了专业级的独立日语词典，支持罗马音，并具有智能的多因素排名。",
        feat_dict_p2: "建立<strong>用户创建的集合</strong>以整洁地组织您的词汇，并轻松将您最喜欢的文章加入书签以便将来阅读。",
        feat_dict_img: "整理您的<br>词汇学习",
        feat_flash_title: "🎴 智能抽认卡",
        feat_flash_p1: "由 FSRS 算法（Anki 背后的科学）提供支持，卡片会在您即将忘记时准确出现。",
        feat_flash_p2: "体验<strong>语境感知抽认卡</strong>：复习和练习与您发现该单词时的特定上下文含义联系在一起。",
        feat_flash_p3: "渐进式难度：汉字 → 读音 → 含义。通过 JLPT 级别（N5-N1）进行筛选，专注于对您目标重要的内容。",
        feat_flash_img: "截图：带 JLPT 筛选的<br>抽认卡界面",
        feat_ai_title: "🤖 AI 写作辅导",
        feat_ai_p1: "真正的魔法：使用您的词汇写出日语句子，获得关于您的优点和改进之处的详细 AI 反馈。",
        feat_ai_p2: "不仅是“对”或“错”——获得关于语法、词汇选择和自然用法的评分反馈。这就是您真正学会使用单词，而不仅仅是识别它们的方法。",
        how_title: "使用说明",
        step1_title: "阅读与收集",
        step1_desc: "浏览文章，点击不认识的单词，将其添加到您的牌组",
        step2_title: "每日复习",
        step2_desc: "抽认卡会根据间隔重复出现——在您快要忘记时进行复习",
        step3_title: "写作练习",
        step3_desc: "在句子中使用您的词汇，获得 AI 反馈，提高您的日语水平",
        step4_title: "追踪进度",
        step4_desc: "看着您的词汇量增加，记忆力随时间提高",
        road_title: "现在与未来",
        road_subtitle: "YominGo 由一名开发者（就是我！）在业余时间构建并积极发展。以下是现在提供的功能和即将推出的功能。",
        live_now: "✓ 现有功能",
        live_1: "真实的日语新闻文章",
        live_2: "FSRS 间隔重复抽认卡与 AI 智能卡片！",
        live_3: "提供详细反馈的 AI 写作练习",
        live_4: "用于即时查词的词典（Beta 版）",
        live_5: "使用各种标签（JLPT，常用，技术等）创建的自定义集合",
        live_6: "多语言支持（英语、中文、韩语和越南语）",
        coming_soon_col: "🚧 即将推出",
        soon_1: "供随时随地学习的离线模式",
        soon_2: "用户自定义文章创建（从文本和扫描图像中）",
        soon_3: "语法练习",
        soon_4: "听力练习",
        support_title: "☕ 支持开发",
        support_desc: "YominGo 是由一个人在业余时间建立的。如果它对您学习日语有帮助，<br>请考虑请我喝杯咖啡——这有助于支付服务器成本并不断推出新功能！",
        footer_built: "用心为日语学习者打造 ❤️",
        footer_contact: "联系我们",
        footer_privacy: "隐私政策"
    },
    vi: {
        nav_features: "Tính năng",
        nav_how: "Cách hoạt động",
        nav_roadmap: "Lộ trình",
        nav_support: "Hỗ trợ",
        hero_title: "Học Tiếng Nhật Qua<br><span class=\"highlight\">Nội Dung Thực Tế & AI</span>",
        hero_subtitle: "Đọc các bài báo thực tế, xây dựng từ vựng với thẻ flashcard và thực hành viết với phản hồi từ AI giúp bạn thực sự tiến bộ.",
        coming_soon: "Sắp Ra Mắt",
        problem_title: "Tại Sao Hầu Hết Ứng Dụng Từ Vựng Không Hiệu Quả",
        prob_context_title: "Không Có Ngữ Cảnh",
        prob_context_desc: "Học các từ đơn lẻ từ các ví dụ trong sách giáo khoa không cho bạn thấy cách tiếng Nhật thực sự được sử dụng.",
        prob_retention_title: "Khả Năng Ghi Nhớ Kém",
        prob_retention_desc: "Nếu không có sự lặp lại ngắt quãng (Spaced Repetition), bạn sẽ quên từ vựng nhanh như khi bạn học chúng.",
        prob_practice_title: "Không Có Thực Hành Viết",
        prob_practice_desc: "Nhận biết từ thì dễ. Sử dụng chúng chính xác trong câu? Đó mới là thử thách thực sự.",
        journey_title: "Hành Trình Học Tập Toàn Diện",
        feat_read_title: "📰 Đọc Tiếng Nhật Thực Tế",
        feat_read_p1: "Duyệt các bài báo tin tức thực tế được viết cho người bản xứ. Chạm vào bất kỳ từ nào để tra cứu từ điển tức thì với hướng dẫn đọc furigana.",
        feat_read_p2: "Công nghệ <strong>Phân Tích Từ Ghép</strong> tiên tiến của chúng tôi phân tích các thuật ngữ tiếng Nhật phức tạp, tách chúng thành các thành phần dễ hiểu.",
        feat_read_p3: "Một cú chạm lưu từ vào bộ bài cá nhân của bạn để thực hành sau. Học từ vựng trong bối cảnh nó thực sự được sử dụng.",
        feat_dict_title: "🔍 Từ Điển Độc Lập & Tổ Chức",
        feat_dict_p1: "Không chỉ là một ứng dụng đọc—YominGo có tính năng từ điển tiếng Nhật độc lập cấp chuyên nghiệp với hỗ trợ Romaji và xếp hạng đa yếu tố thông minh.",
        feat_dict_p2: "Xây dựng <strong>Bộ Sưu Tập Của Bạn</strong> để sắp xếp gọn gàng từ vựng của bạn và dễ dàng đánh dấu các bài báo yêu thích của bạn để đọc trong tương lai.",
        feat_dict_img: "Tổ chức<br>Từ vựng của bạn",
        feat_flash_title: "🎴 Thẻ Flashcard Thông Minh",
        feat_flash_p1: "Được hỗ trợ bởi thuật toán FSRS (khoa học đằng sau Anki), các thẻ xuất hiện chính xác khi bạn sắp quên chúng.",
        feat_flash_p2: "Trải nghiệm <strong>Thẻ Flashcard Nhận Thức Ngữ Cảnh</strong>: đánh giá và bài tập được gắn với ý nghĩa ngữ cảnh cụ thể mà bạn tìm thấy từ đó.",
        feat_flash_p3: "Độ khó tăng dần: Kanji → Cách đọc → Ý nghĩa. Lọc theo cấp độ JLPT (N5-N1) để tập trung vào những gì quan trọng cho mục tiêu của bạn.",
        feat_flash_img: "Ảnh chụp: Giao diện thẻ Flashcard<br>với bộ lọc JLPT",
        feat_ai_title: "🤖 Gia Sư Viết AI",
        feat_ai_p1: "Phép thuật thực sự: Viết các câu tiếng Nhật sử dụng từ vựng của bạn, nhận phản hồi AI chi tiết về những gì bạn đã làm đúng và những gì cần cải thiện.",
        feat_ai_p2: "Không chỉ là \"đúng\" hay \"sai\"—nhận phản hồi được chấm điểm về ngữ pháp, lựa chọn từ và cách sử dụng tự nhiên. Đây là cách bạn thực sự học cách sử dụng từ, không chỉ nhận biết chúng.",
        how_title: "Cách Hoạt Động",
        step1_title: "Đọc & Thu Thập",
        step1_desc: "Duyệt bài viết, chạm vào những từ bạn không biết, thêm chúng vào bộ bài của bạn",
        step2_title: "Ôn Tập Hàng Ngày",
        step2_desc: "Thẻ Flashcard xuất hiện dựa trên sự lặp lại ngắt quãng—ôn tập những gì bạn sắp quên",
        step3_title: "Thực Hành Viết",
        step3_desc: "Sử dụng từ vựng của bạn trong câu, nhận phản hồi AI, cải thiện tiếng Nhật của bạn",
        step4_title: "Theo Dõi Tiến Trình",
        step4_desc: "Theo dõi vốn từ vựng của bạn tăng lên và khả năng ghi nhớ cải thiện theo thời gian",
        road_title: "Hiện Tại & Tương Lai",
        road_subtitle: "YominGo được xây dựng bởi một nhà phát triển (là tôi!) và đang tích cực phát triển. Dưới đây là những gì hiện có và những gì sắp ra mắt.",
        live_now: "✓ Hiện Đang Có",
        live_1: "Bài báo Tin Tức Tiếng Nhật thực tế",
        live_2: "Thẻ flashcard lặp lại ngắt quãng FSRS và Thẻ thông minh do AI cung cấp!",
        live_3: "Bài tập viết do AI hỗ trợ với phản hồi chi tiết",
        live_4: "Từ điển (beta) để tra cứu từ tức thì",
        live_5: "Bộ sưu tập tùy chỉnh tạo bằng cách sử dụng nhiều thẻ (JLPT, Thông dụng, Công nghệ..v.v.)",
        live_6: "Hỗ trợ đa ngôn ngữ (tiếng Anh, tiếng Trung, tiếng Hàn và tiếng Việt)",
        coming_soon_col: "🚧 Sắp Ra Mắt",
        soon_1: "Chế độ ngoại tuyến để học mọi lúc mọi nơi",
        soon_2: "Người dùng tùy chỉnh tạo bài viết (từ văn bản và quét hình ảnh)",
        soon_3: "Thực hành ngữ pháp",
        soon_4: "Thực hành nghe",
        support_title: "☕ Hỗ Trợ Phát Triển",
        support_desc: "YominGo được xây dựng bởi một người trong thời gian rảnh rỗi của họ. Nếu nó giúp bạn học tiếng Nhật,<br>hãy cân nhắc mua cho tôi một ly cà phê—nó giúp trang trải chi phí máy chủ và giữ cho các tính năng mới luôn ra mắt!",
        footer_built: "Được xây dựng với ❤️ dành cho người học tiếng Nhật",
        footer_contact: "Liên hệ",
        footer_privacy: "Chính sách bảo mật"
    }
};

function changeLanguage(lang) {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });
    
    document.documentElement.lang = lang;
}

// Ensure elements get properly updated on initial load if needed
document.addEventListener('DOMContentLoaded', () => {
    // Check if browser has a preferred language that matches
    const browserLang = navigator.language.split('-')[0];
    if (translations[browserLang]) {
        changeLanguage(browserLang);
    }
});
