const translations = {
    en: {
        nav_features: "Features",
        nav_how: "How It Works",
        nav_roadmap: "Roadmap",
        nav_support: "Support",
        hero_title: "Learn Japanese Through<br><span class=\"highlight\">Real Content & AI Practice</span>",
        hero_subtitle: "Read authentic articles, build vocabulary with flashcards, and practice writing with AI-powered feedback that actually helps you improve.",
        coming_soon: "Coming Soon",
        problem_title: "Why Most Vocabulary Apps Don't Work",
        prob_context_title: "No Context",
        prob_context_desc: "Learning isolated words from textbook examples doesn't show you how Japanese is actually used.",
        prob_retention_title: "Poor Retention",
        prob_retention_desc: "Without spaced repetition, you forget words as fast as you learn them.",
        prob_practice_title: "No Production Practice",
        prob_practice_desc: "Recognizing words is easy. Using them correctly in sentences? That's the real challenge.",
        journey_title: "Comprehensive Learning Journey",
        feat_read_title: "📰 Read Real Japanese",
        feat_read_p1: "Read articles at your own pace — choose from Beginner, Intermediate, or Advanced levels. Tap any word for instant dictionary lookup with furigana reading guides.",
        feat_read_p2: "Our advanced <strong>Compound Word Breakdown</strong> technology analyzes complex Japanese terms, splitting them into easily understandable sub-components.",
        feat_read_p3: "One tap saves words to your personal deck for practice later. Learn vocabulary in the context it's actually used.",
        feat_dict_title: "🔍 Standalone Dictionary",
        feat_dict_p1: "Not just a reader—YominGo features a professional-grade standalone Japanese dictionary with Romaji support and intelligent multi-factor ranking.",
        feat_dict_p2: "Select text in other apps and instantly open YominGo Dictionary. Perfect for reading articles in Chrome or any browser—easily add words to your Collections without leaving your workflow.",
        feat_dict_img: "Professional<br>Dictionary",
        feat_coll_title: "📁 Collection-based Organization",
        feat_coll_p1: "Build <strong>User-Created Collections</strong> organically by saving words as you read articles—every tap adds vocabulary in the context it appeared.",
        feat_coll_p2: "Or prepopulate a Collection instantly from the dictionary using existing tags like JLPT, Common, or Tech.",
        feat_coll_img: "Organize by<br>Your Needs",
        smart_title: "🎴 YominGo Smart Cards™",
        smart_tagline: "The feature that sets us apart from every other app.",
        smart_intro: "Smart Cards combine FSRS spaced repetition (the same algorithm behind Anki) with AI-graded writing practice in a single review flow:",
        smart_step1: "FSRS scheduling (when to review)",
        smart_step2: "You type sentences using the target word",
        smart_step3: "AI evaluates: correct word usage + grammar + natural flow",
        smart_step4: "Detailed feedback and scoring",
        how_title: "How It Works",
        step1_title: "Read & Collect",
        step1_desc: "Browse articles, tap words you don't know, add them to your deck",
        step2_title: "Review Daily",
        step2_desc: "Flashcards appear based on spaced repetition—review what you're about to forget",
        step3_title: "Practice Writing",
        step3_desc: "Use your vocabulary in sentences, get AI feedback, improve your Japanese",
        step4_title: "Track Progress",
        step4_desc: "Watch your vocabulary grow and retention improve over time",
        road_title: "What's Now & What's Next",
        road_subtitle: "YominGo is built by one developer (me!) and actively growing. Here's what works today and what's coming soon.",
        live_now: "✓ Live Now",
        live_1: "Real Japanese News articles",
        live_2: "FSRS spaces repetition flashcards and AI powered Smart-cards!",
        live_3: "AI-powered writing exercises with detailed feedback",
        live_4: "Dictionary for instant word lookup — 200k+ words <small class=\"dict-note\">(Korean, Chinese, and Vietnamese translations available for the common 27k words)</small>",
        live_5: "Custom collections create using wide range of tags (JLPT, Common,Tech..etc)",
        live_6: "Multi-language support (English, Simplified Chinese, Traditional Chinese, Korean, and Vietnamese)",
        coming_soon_col: "🚧 Coming Soon",
        soon_kanji: "Kanji writing practice — solidify kanji into long-term memory through stroke-order drills",
        soon_1: "Expanded offline support for studying anywhere",
        soon_2: "Custom user created article creation (from text and scanning images)",
        soon_3: "Grammer practice",
        soon_4: "Listening practice",
        soon_dict_title: "Dictionary",
        soon_dict_1: "Conjugations & forms",
        soon_dict_2: "Full dictionary support for 4 languages",
        soon_dict_3: "Kanji with radicals and similar kanji links",
        support_title: "☕ Support Development",
        support_desc: "YominGo is built by one person in their spare time. If it's helping you learn Japanese,<br>consider buying me a coffee—it helps cover server costs and keeps new features coming!",
        footer_built: "Built with ❤️ for Japanese learners",
        footer_contact: "Contact",
        footer_privacy: "Privacy Policy"
    },
    ko: {
        nav_features: "기능",
        nav_how: "작동 방식",
        nav_roadmap: "로드맵",
        nav_support: "지원",
        hero_title: "실제 콘텐츠 및 AI 연습으로<br><span class=\"highlight\">일본어 배우기</span>",
        hero_subtitle: "실제 기사를 읽고 플래시 카드로 어휘를 쌓으며, AI 피드백을 통해 실제로 실력을 향상시키는 작문 연습을 해보세요.",
        coming_soon: "출시 예정",
        problem_title: "대부분의 단어 앱이 효과가 없는 이유",
        prob_context_title: "문맥 부족",
        prob_context_desc: "교과서 예문에서 단어를 따로 배우는 것은 일본어가 실제로 어떻게 사용되는지 보여주지 않습니다.",
        prob_retention_title: "낮은 기억 유지율",
        prob_retention_desc: "간격 반복(Spaced Repetition) 없이 배우면 금방 잊어버리게 됩니다.",
        prob_practice_title: "생산 연습 부족",
        prob_practice_desc: "단어를 알아보는 것은 쉽습니다. 문장에서 올바르게 사용하는 것이 진짜 도전입니다.",
        journey_title: "종합적인 학습 여정",
        feat_read_title: "📰 실제 일본어 읽기",
        feat_read_p1: "자신의 속도에 맞게 기사를 읽어보세요 — 초급, 중급, 고급 수준 중에서 선택하세요. 단어를 터치하여 즉시 사전을 찾고 후리가나를 볼 수 있습니다.",
        feat_read_p2: "저희의 고급 <strong>복합어 분석</strong> 기술은 복잡한 일본어 용어를 쉽게 이해할 수 있는 하위 구성 요소로 분할합니다.",
        feat_read_p3: "터치 한 번으로 개인 덱에 단어를 저장하여 나중에 연습하세요. 실제 사용되는 문맥에서 어휘를 배우십시오.",
        feat_dict_title: "🔍 독립형 사전",
        feat_dict_p1: "단순한 리더기가 아닙니다—YominGo는 로마자 지원 및 지능적인 다중 요인 순위 지정을 갖춘 전문가급 일본어 사전을 제공합니다.",
        feat_dict_p2: "다른 앱에서 텍스트를 선택하여 즉시 YominGo 사전을 엽니다. Chrome이나 다른 브라우저에서 기사를 읽을 때 완벽합니다—워크플로우를 벗어나지 않고 쉽게 단어를 컬렉션에 추가하세요.",
        feat_dict_img: "전문가급<br>사전",
        feat_coll_title: "📁 컬렉션 기반 체계화",
        feat_coll_p1: "기사를 읽으며 단어를 저장하여 <strong>사용자 생성 컬렉션</strong>을 자연스럽게 구축하세요—탭 한 번으로 단어가 등장한 문맥과 함께 어휘에 추가됩니다.",
        feat_coll_p2: "또는 JLPT, 일반, 기술 같은 기존 태그를 사용해 사전에서 컬렉션을 즉시 미리 채울 수도 있습니다.",
        feat_coll_img: "필요에 따라<br>체계화하기",
        smart_title: "🎴 YominGo 스마트 카드™",
        smart_tagline: "다른 모든 앱과 차별화되는 핵심 기능.",
        smart_intro: "스마트 카드는 FSRS 간격 반복(Anki에서 사용하는 것과 동일한 알고리즘)과 AI 채점 작문 연습을 하나의 복습 흐름으로 결합합니다:",
        smart_step1: "FSRS 스케줄링 (복습 시점 결정)",
        smart_step2: "대상 단어를 사용해 문장을 입력합니다",
        smart_step3: "AI 평가: 올바른 단어 사용 + 문법 + 자연스러운 흐름",
        smart_step4: "상세한 피드백과 점수",
        how_title: "작동 방식",
        step1_title: "읽기 및 수집",
        step1_desc: "기사를 탐색하고, 모르는 단어를 터치하여 덱에 추가하세요.",
        step2_title: "매일 복습",
        step2_desc: "간격 반복에 따라 플래시카드가 나타납니다—잊어버리기 직전에 복습하세요.",
        step3_title: "작문 연습",
        step3_desc: "문장에서 어휘를 사용하고, AI 피드백을 받아 일본어 실력을 향상시키세요.",
        step4_title: "진행 상황 추적",
        step4_desc: "시간이 지남에 따라 어휘가 늘어나고 기억력이 향상되는 것을 지켜보세요.",
        road_title: "현재와 미래",
        road_subtitle: "YominGo는 한 명의 개발자(저예요!)가 만들고 꾸준히 성장하고 있습니다. 현재 제공되는 기능과 곧 출시될 기능입니다.",
        live_now: "✓ 현재 기능",
        live_1: "실제 일본어 뉴스 기사",
        live_2: "FSRS 간격 반복 플래시카드 및 AI 기반 스마트 카드!",
        live_3: "상세한 피드백이 있는 AI 기반 작문 연습",
        live_4: "즉시 단어 검색을 위한 사전 — 200,000개 이상의 단어 <small class=\"dict-note\">(한국어, 중국어, 베트남어 번역은 일반적인 27,000개 단어에 대해 제공)</small>",
        live_5: "다양한 태그(JLPT, 일반, 기술 등)를 사용한 맞춤형 컬렉션 생성",
        live_6: "다국어 지원 (영어, 간체 중국어, 번체 중국어, 한국어, 베트남어)",
        coming_soon_col: "🚧 출시 예정",
        soon_kanji: "한자 쓰기 연습 — 획순 드릴로 한자를 장기 기억에 완전히 새기세요",
        soon_1: "어디서나 공부할 수 있도록 오프라인 지원 확대",
        soon_2: "사용자 맞춤 기사 생성 (텍스트 및 이미지 스캔에서)",
        soon_3: "문법 연습",
        soon_4: "듣기 연습",
        soon_dict_title: "사전",
        soon_dict_1: "활용 및 어형 변화",
        soon_dict_2: "4개 언어에 대한 완전한 사전 지원",
        soon_dict_3: "부수 및 유사 한자 링크가 포함된 한자",
        support_title: "☕ 개발 지원",
        support_desc: "YominGo는 여가 시간에 한 사람이 만들었습니다. 일본어 학습에 도움이 된다면<br>커피 한 잔을 사주세요—서버 비용을 충당하고 새로운 기능을 추가하는 데 큰 도움이 됩니다!",
        footer_built: "일본어 학습자를 위해 ❤️로 만들었습니다",
        footer_contact: "문의하기",
        footer_privacy: "개인정보 보호정책"
    },
    zh: {
        nav_features: "功能",
        nav_how: "使用说明",
        nav_roadmap: "路线图",
        nav_support: "支持",
        hero_title: "通过真实语境与 AI 练习<br><span class=\"highlight\">学习日语</span>",
        hero_subtitle: "阅读真实的新闻文章，通过抽任卡积累词汇，并通过提供即时反馈的 AI 辅导练习写作，真正提高你的日语水平。",
        coming_soon: "敬请期待",
        problem_title: "为什么大多数单词应用没用",
        prob_context_title: "缺乏语境",
        prob_context_desc: "仅从教科书例句中孤立地学习单词，无法了解日语在现实中的实际用法。",
        prob_retention_title: "记忆留存率低",
        prob_retention_desc: "如果没有间隔重复，背过的单词很快就会被遗忘。",
        prob_practice_title: "缺乏输出练习",
        prob_practice_desc: "认出单词很容易。如何在句子中正确使用它们？这才是真正的挑战。",
        journey_title: "全面的学习旅程",
        feat_read_title: "📰 阅读真实日语",
        feat_read_p1: "按照自己的节奏阅读文章 — 选择初级、中级或高级水平。点击任何单词即可进行即时词典查询并显示振假名阅读指南。",
        feat_read_p2: "我们先进的<strong>复合词拆分</strong>技术可分析复杂的日语词汇，将其拆分为易于理解的子成分。",
        feat_read_p3: "只需点击一下，即可将单词保存到您的个人牌组中以供日后练习。在实际使用的语境中学习词汇。",
        feat_dict_title: "🔍 独立词典",
        feat_dict_p1: "不仅仅是一个阅读器——YominGo 配备了专业级的独立日语词典，支持罗马音，并具有智能的多因素排名。",
        feat_dict_p2: "在其他应用中选择文本即可立即打开YominGo词典。非常适合在Chrome或其他浏览器中阅读文章——无需离开工作流程即可轻松将单词添加到集合中。",
        feat_dict_img: "专业级<br>词典",
        feat_coll_title: "📁 集合式组织",
        feat_coll_p1: "在阅读文章时保存单词，自然地构建<strong>用户创建的集合</strong>——每次点击都会将词汇连同其出现的上下文一起添加。",
        feat_coll_p2: "或使用 JLPT、常用、技术等现有标签从词典中即时预填一个集合。",
        feat_coll_img: "按需<br>组织",
        smart_title: "🎴 YominGo 智能卡™",
        smart_tagline: "让我们与其他所有应用程序与众不同的核心功能。",
        smart_intro: "智能卡将 FSRS 间隔重复（与 Anki 背后相同的算法）与 AI 评分的写作练习结合在一个复习流程中：",
        smart_step1: "FSRS 调度（决定何时复习）",
        smart_step2: "您使用目标单词输入句子",
        smart_step3: "AI 评估：正确的单词使用 + 语法 + 自然流畅",
        smart_step4: "详细的反馈和评分",
        how_title: "使用说明",
        step1_title: "阅读与收集",
        step1_desc: "浏览文章，点击不认识的单词，将其添加到您的牌组",
        step2_title: "每日复习",
        step2_desc: "抽认卡会根据间隔重复出现——在您快要忘记时进行复习",
        step3_title: "写作练习",
        step3_desc: "在句子中使用您的词汇，获得 AI 反馈，提高您的日语水平",
        step4_title: "追踪进度",
        step4_desc: "看着您的词汇量增加，记忆力随时间提高",
        road_title: "现在与未来",
        road_subtitle: "YominGo 由一名开发者（就是我！）在业余时间构建并积极发展。以下是现在提供的功能和即将推出的功能。",
        live_now: "✓ 现有功能",
        live_1: "真实的日语新闻文章",
        live_2: "FSRS 间隔重复抽认卡与 AI 智能卡片！",
        live_3: "提供详细反馈的 AI 写作练习",
        live_4: "用于即时查词的词典 —— 20万+ 单词 <small class=\"dict-note\">（韩语、中文、越南语翻译仅适用于常用的 2.7万 单词）</small>",
        live_5: "使用各种标签（JLPT，常用，技术等）创建的自定义集合",
        live_6: "多语言支持（英语、简体中文、繁体中文、韩语和越南语）",
        coming_soon_col: "🚧 即将推出",
        soon_kanji: "汉字书写练习 — 通过笔顺练习将汉字深刻印入长期记忆",
        soon_1: "扩展离线支持，随时随地学习",
        soon_2: "用户自定义文章创建（从文本和扫描图像中）",
        soon_3: "语法练习",
        soon_4: "听力练习",
        soon_dict_title: "词典",
        soon_dict_1: "动词变形和词形变化",
        soon_dict_2: "支持 4 种语言的完整词典",
        soon_dict_3: "汉字（含部首及相似汉字链接）",
        support_title: "☕ 支持开发",
        support_desc: "YominGo 是由一个人在业余时间建立的。如果它对您学习日语有帮助，<br>请考虑请我喝杯咖啡——这有助于支付服务器成本并不断推出新功能！",
        footer_built: "用心为日语学习者打造 ❤️",
        footer_contact: "联系我们",
        footer_privacy: "隐私政策"
    },
    "zh-TW": {
        nav_features: "功能",
        nav_how: "使用說明",
        nav_roadmap: "路線圖",
        nav_support: "支援",
        hero_title: "透過真實語境與 AI 練習<br><span class=\"highlight\">學習日語</span>",
        hero_subtitle: "閱讀真實的新聞文章，透過抽認卡累積詞彙，並透過 AI 即時反饋的寫作練習，真正提升你的日語能力。",
        coming_soon: "即將推出",
        problem_title: "為什麼大多數單字應用沒有效果",
        prob_context_title: "缺乏語境",
        prob_context_desc: "只從教科書例句中孤立地學習單字，無法了解日語在現實中的實際用法。",
        prob_retention_title: "記憶留存率低",
        prob_retention_desc: "若沒有間隔重複，背過的單字很快就會被遺忘。",
        prob_practice_title: "缺乏輸出練習",
        prob_practice_desc: "認識單字很容易，但如何在句子中正確使用？這才是真正的挑戰。",
        journey_title: "全方位學習旅程",
        feat_read_title: "📰 閱讀真實日語",
        feat_read_p1: "依照自己的節奏閱讀文章 — 選擇初級、中級或高級程度。點擊任何單字即可即時查詢詞典，並顯示假名標音。",
        feat_read_p2: "我們先進的<strong>複合詞拆解</strong>技術可分析複雜的日語詞彙，將其拆分為易於理解的子成分。",
        feat_read_p3: "只需點擊一下，即可將單字儲存到個人牌組以供日後練習。在實際使用的語境中學習詞彙。",
        feat_dict_title: "🔍 獨立詞典",
        feat_dict_p1: "不僅僅是閱讀器——YominGo 配備了專業級的獨立日語詞典，支援羅馬拼音，並具備智慧多因素排名。",
        feat_dict_p2: "在其他應用程式中選取文字即可立即開啟 YominGo 詞典。非常適合在 Chrome 或其他瀏覽器中閱讀文章——無需離開工作流程即可輕鬆將單字加入收藏。",
        feat_dict_img: "專業級<br>詞典",
        feat_coll_title: "📁 收藏式整理",
        feat_coll_p1: "在閱讀文章時儲存單字，自然地建立<strong>使用者自訂收藏</strong>——每次點擊都會將詞彙連同出現的語境一起加入。",
        feat_coll_p2: "或使用 JLPT、常用、技術等現有標籤從詞典中即時預填一個收藏。",
        feat_coll_img: "按需<br>整理",
        smart_title: "🎴 YominGo 智慧卡™",
        smart_tagline: "讓我們與其他所有應用程式與眾不同的核心功能。",
        smart_intro: "智慧卡將 FSRS 間隔重複（與 Anki 背後相同的演算法）與 AI 評分寫作練習結合在單一複習流程中：",
        smart_step1: "FSRS 排程（決定何時複習）",
        smart_step2: "您使用目標單字輸入句子",
        smart_step3: "AI 評估：正確的單字使用 + 文法 + 自然流暢度",
        smart_step4: "詳細的反饋與評分",
        how_title: "使用方法",
        step1_title: "閱讀與收集",
        step1_desc: "瀏覽文章，點擊不認識的單字，將其加入牌組",
        step2_title: "每日複習",
        step2_desc: "抽認卡會根據間隔重複出現——在您快要忘記時進行複習",
        step3_title: "寫作練習",
        step3_desc: "在句子中使用詞彙，獲得 AI 反饋，提升您的日語水準",
        step4_title: "追蹤進度",
        step4_desc: "看著您的詞彙量增加，記憶力隨時間提升",
        road_title: "現在與未來",
        road_subtitle: "YominGo 由一位開發者（就是我！）在業餘時間建立並積極成長中。以下是現有功能和即將推出的功能。",
        live_now: "✓ 現有功能",
        live_1: "真實的日語新聞文章",
        live_2: "FSRS 間隔重複抽認卡與 AI 智慧卡！",
        live_3: "提供詳細反饋的 AI 寫作練習",
        live_4: "用於即時查詞的詞典 —— 20萬+ 單字 <small class=\"dict-note\">（韓語、中文、越南語翻譯僅適用於常用的 2.7萬 單字）</small>",
        live_5: "使用各種標籤（JLPT、常用、技術等）建立的自訂收藏",
        live_6: "多語言支援（英語、簡體中文、繁體中文、韓語和越南語）",
        coming_soon_col: "🚧 即將推出",
        soon_kanji: "漢字書寫練習 — 透過筆順練習將漢字深刻印入長期記憶",
        soon_1: "擴展離線支援，隨時隨地學習",
        soon_2: "使用者自訂文章建立（從文字和掃描圖像中）",
        soon_3: "文法練習",
        soon_4: "聽力練習",
        soon_dict_title: "詞典",
        soon_dict_1: "動詞變化與詞形變化",
        soon_dict_2: "支援 4 種語言的完整詞典",
        soon_dict_3: "漢字（含部首及相似漢字連結）",
        support_title: "☕ 支持開發",
        support_desc: "YominGo 是由一個人在業餘時間建立的。如果它對您學習日語有幫助，<br>請考慮請我喝杯咖啡——這有助於支付伺服器費用並持續推出新功能！",
        footer_built: "用心為日語學習者打造 ❤️",
        footer_contact: "聯絡我們",
        footer_privacy: "隱私政策"
    },
    vi: {
        nav_features: "Tính năng",
        nav_how: "Cách hoạt động",
        nav_roadmap: "Lộ trình",
        nav_support: "Hỗ trợ",
        hero_title: "Học Tiếng Nhật Qua<br><span class=\"highlight\">Nội Dung Thực Tế & AI</span>",
        hero_subtitle: "Đọc các bài báo thực tế, xây dựng từ vựng với thẻ flashcard và thực hành viết với phản hồi từ AI giúp bạn thực sự tiến bộ.",
        coming_soon: "Sắp Ra Mắt",
        problem_title: "Tại Sao Hầu Hết Ứng Dụng Từ Vựng Không Hiệu Quả",
        prob_context_title: "Không Có Ngữ Cảnh",
        prob_context_desc: "Học các từ đơn lẻ từ các ví dụ trong sách giáo khoa không cho bạn thấy cách tiếng Nhật thực sự được sử dụng.",
        prob_retention_title: "Khả Năng Ghi Nhớ Kém",
        prob_retention_desc: "Nếu không có sự lặp lại ngắt quãng (Spaced Repetition), bạn sẽ quên từ vựng nhanh như khi bạn học chúng.",
        prob_practice_title: "Không Có Thực Hành Viết",
        prob_practice_desc: "Nhận biết từ thì dễ. Sử dụng chúng chính xác trong câu? Đó mới là thử thách thực sự.",
        journey_title: "Hành Trình Học Tập Toàn Diện",
        feat_read_title: "📰 Đọc Tiếng Nhật Thực Tế",
        feat_read_p1: "Đọc bài viết theo tốc độ của bạn — chọn từ cấp độ Sơ cấp, Trung cấp hoặc Nâng cao. Chạm vào bất kỳ từ nào để tra cứu từ điển tức thì với hướng dẫn đọc furigana.",
        feat_read_p2: "Công nghệ <strong>Phân Tích Từ Ghép</strong> tiên tiến của chúng tôi phân tích các thuật ngữ tiếng Nhật phức tạp, tách chúng thành các thành phần dễ hiểu.",
        feat_read_p3: "Một cú chạm lưu từ vào bộ bài cá nhân của bạn để thực hành sau. Học từ vựng trong bối cảnh nó thực sự được sử dụng.",
        feat_dict_title: "🔍 Từ Điển Độc Lập",
        feat_dict_p1: "Không chỉ là một ứng dụng đọc—YominGo có tính năng từ điển tiếng Nhật độc lập cấp chuyên nghiệp với hỗ trợ Romaji và xếp hạng đa yếu tố thông minh.",
        feat_dict_p2: "Chọn văn bản trong các ứng dụng khác và mở ngay từ điển YominGo. Hoàn hảo cho việc đọc bài viết trong Chrome hoặc bất kỳ trình duyệt nào—dễ dàng thêm từ vào Bộ Sưu Tập của bạn mà không cần rời khỏi quy trình làm việc.",
        feat_dict_img: "Từ điển<br>Chuyên Nghiệp",
        feat_coll_title: "📁 Tổ Chức Theo Bộ Sưu Tập",
        feat_coll_p1: "Xây dựng <strong>Bộ Sưu Tập Do Người Tạo</strong> một cách tự nhiên bằng cách lưu các từ trong khi đọc bài viết—mỗi lần chạm sẽ thêm từ vựng kèm theo ngữ cảnh nó xuất hiện.",
        feat_coll_p2: "Hoặc tạo trước một Bộ Sưu Tập ngay lập tức từ từ điển bằng cách sử dụng các thẻ hiện có như JLPT, Thông dụng hoặc Công nghệ.",
        feat_coll_img: "Tổ Chúc<br>Theo Nhu Cầu",
        smart_title: "🎴 Thẻ Thông Minh YominGo™",
        smart_tagline: "Tính năng làm chúng tôi khác biệt với mọi ứng dụng khác.",
        smart_intro: "Thẻ Thông Minh kết hợp lặp lại ngắt quãng FSRS (cùng thuật toán đứng sau Anki) với luyện viết được AI chấm điểm trong một quy trình ôn tập duy nhất:",
        smart_step1: "Lên lịch FSRS (khi nào ôn tập)",
        smart_step2: "Bạn nhập câu sử dụng từ mục tiêu",
        smart_step3: "AI đánh giá: cách dùng từ đúng + ngữ pháp + sự tự nhiên",
        smart_step4: "Phản hồi và đánh giá chi tiết",
        how_title: "Cách Hoạt Động",
        step1_title: "Đọc & Thu Thập",
        step1_desc: "Duyệt bài viết, chạm vào những từ bạn không biết, thêm chúng vào bộ bài của bạn",
        step2_title: "Ôn Tập Hàng Ngày",
        step2_desc: "Thẻ Flashcard xuất hiện dựa trên sự lặp lại ngắt quãng—ôn tập những gì bạn sắp quên",
        step3_title: "Thực Hành Viết",
        step3_desc: "Sử dụng từ vựng của bạn trong câu, nhận phản hồi AI, cải thiện tiếng Nhật của bạn",
        step4_title: "Theo Dõi Tiến Trình",
        step4_desc: "Theo dõi vốn từ vựng của bạn tăng lên và khả năng ghi nhớ cải thiện theo thời gian",
        road_title: "Hiện Tại & Tương Lai",
        road_subtitle: "YominGo được xây dựng bởi một nhà phát triển (là tôi!) và đang tích cực phát triển. Dưới đây là những gì hiện có và những gì sắp ra mắt.",
        live_now: "✓ Hiện Đang Có",
        live_1: "Bài báo Tin Tức Tiếng Nhật thực tế",
        live_2: "Thẻ flashcard lặp lại ngắt quãng FSRS và Thẻ thông minh do AI cung cấp!",
        live_3: "Bài tập viết do AI hỗ trợ với phản hồi chi tiết",
        live_4: "Từ điển tra cứu từ tức thì — 200k+ từ <small class=\"dict-note\">(Bản dịch tiếng Hàn, tiếng Trung và tiếng Việt có sẵn cho 27k từ thông dụng)</small>",
        live_5: "Bộ sưu tập tùy chỉnh tạo bằng cách sử dụng nhiều thẻ (JLPT, Thông dụng, Công nghệ..v.v.)",
        live_6: "Hỗ trợ đa ngôn ngữ (tiếng Anh, tiếng Trung giản thể, tiếng Trung phồn thể, tiếng Hàn và tiếng Việt)",
        coming_soon_col: "🚧 Sắp Ra Mắt",
        soon_kanji: "Luyện viết Kanji — củng cố Kanji vào trí nhớ dài hạn qua luyện tập nét chữ",
        soon_1: "Mở rộng hỗ trợ ngoại tuyến để học mọi lúc mọi nơi",
        soon_2: "Người dùng tùy chỉnh tạo bài viết (từ văn bản và quét hình ảnh)",
        soon_3: "Thực hành ngữ pháp",
        soon_4: "Thực hành nghe",
        soon_dict_title: "Từ điển",
        soon_dict_1: "Chia động từ & dạng từ",
        soon_dict_2: "Hỗ trợ từ điển đầy đủ cho 4 ngôn ngữ",
        soon_dict_3: "Kanji với bộ thủ và liên kết Kanji tương tự",
        support_title: "☕ Hỗ Trợ Phát Triển",
        support_desc: "YominGo được xây dựng bởi một người trong thời gian rảnh rỗi của họ. Nếu nó giúp bạn học tiếng Nhật,<br>hãy cân nhắc mua cho tôi một ly cà phê—nó giúp trang trải chi phí máy chủ và giữ cho các tính năng mới luôn ra mắt!",
        footer_built: "Được xây dựng với ❤️ dành cho người học tiếng Nhật",
        footer_contact: "Liên hệ",
        footer_privacy: "Chính sách bảo mật"
    }
};

function changeLanguage(lang) {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });
    
    document.documentElement.lang = lang;
}

document.addEventListener('DOMContentLoaded', () => {
    const full = navigator.language;
    const short = full.split('-')[0];
    if (full === 'zh-TW' || full === 'zh-Hant' || full === 'zh-HK') {
        changeLanguage('zh-TW');
    } else if (translations[short]) {
        changeLanguage(short);
    }
});
